"""Collect only the font files the film actually needs.

Reads every character used in content/ and scenes/ (plus ASCII), then copies
the @fontsource woff2 chunks whose unicode-range covers any of them and writes
fonts/fonts.css. Re-run after changing on-screen copy.

  python3 fonts/build_fonts.py [--cache /tmp/claude-0/fontcache]

The cache holds the unpacked npm packages (npm pack @fontsource/<name>).
"""
import argparse
import re
import shutil
import subprocess
from pathlib import Path

FILM = Path(__file__).resolve().parent.parent
FAMILIES = {  # package -> css files to use
    "ibm-plex-sans": ["400.css", "500.css", "600.css"],
    "ibm-plex-mono": ["400.css", "500.css"],
    "source-serif-4": ["400.css", "600.css", "400-italic.css"],
    "noto-sans-sc": ["400.css", "500.css", "700.css"],
    "noto-serif-sc": ["400.css", "600.css"],
}


def ranges(spec):
    for part in spec.split(","):
        part = part.strip().upper().removeprefix("U+")
        if "-" in part:
            a, b = part.split("-")
            yield int(a, 16), int(b, 16)
        elif "?" in part:
            yield int(part.replace("?", "0"), 16), int(part.replace("?", "F"), 16)
        else:
            yield int(part, 16), int(part, 16)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", default="/tmp/claude-0/fontcache")
    cache = Path(ap.parse_args().cache)
    cache.mkdir(parents=True, exist_ok=True)

    chars = {ord(c) for c in map(chr, range(0x20, 0x7F))}
    chars |= {0x2014, 0x2019, 0x201C, 0x201D, 0x2026, 0x00B7, 0x2192, 0x2713, 0x00D7, 0x2212}
    for p in list((FILM / "content").rglob("*.js")) + list((FILM / "scenes").rglob("*.js")) + list((FILM / "content").rglob("*.json")):
        chars |= {ord(c) for c in p.read_text(encoding="utf-8")}

    out = FILM / "fonts" / "files"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    css_out, total = [], 0
    for fam, files in FAMILIES.items():
        pkg = cache / f"{fam}" / "package"
        if not pkg.exists():
            tgz = subprocess.run(["npm", "pack", "-q", f"@fontsource/{fam}"], cwd=cache, capture_output=True, text=True, check=True).stdout.strip().splitlines()[-1]
            (cache / fam).mkdir(exist_ok=True)
            subprocess.run(["tar", "xzf", tgz, "-C", fam], cwd=cache, check=True)
        for cssf in files:
            for block in re.findall(r"@font-face\s*{[^}]*}", (pkg / cssf).read_text()):
                ur = re.search(r"unicode-range:\s*([^;]+);", block)
                if ur and not any(any(a <= c <= b for c in chars) for a, b in ranges(ur.group(1))):
                    continue
                woff2 = re.search(r"url\(\./files/([^)]+\.woff2)\)", block).group(1)
                shutil.copy(pkg / "files" / woff2, out / woff2)
                total += (out / woff2).stat().st_size
                block = re.sub(r"src:[^;]+;", f"src: url(files/{woff2}) format('woff2');", block)
                block = block.replace("font-display: swap", "font-display: block")
                css_out.append(block)
    (FILM / "fonts" / "fonts.css").write_text("/* generated by build_fonts.py */\n" + "\n".join(css_out) + "\n")
    print(f"{len(css_out)} faces, {total / 1e6:.1f} MB, {len(chars)} chars")


if __name__ == "__main__":
    main()
