"""Generated by scripts/pin_codex.py -- do not edit by hand."""

from typing import Any

CODEX_VERSION = "0.160.0"

WHEELS: dict[str, dict[str, Any]] = {
    "win32/amd64": {
        "filename": "openai_codex_cli_bin-0.160.0-py3-none-win_amd64.whl",
        "url": "https://files.pythonhosted.org/packages/60/3c/3d5936011336a6e88b03fbfe532afe50527d534eacba5cfd2d4c9ec35ada/openai_codex_cli_bin-0.160.0-py3-none-win_amd64.whl",
        "sha256": "a1245cc0c7d390d22af4920d512ceae8519dee2cf51d8eec56f3899861a8160a",
        "size": 149416482,
        "members": {
            "codex_cli_bin/bin/codex.exe": {
                "sha256": "fdda5fa3cf3fb3d000b876720742857676293e4315e4b045fae6f8bd7e866d1d",
                "size": 326872368,
            },
            "codex_cli_bin/codex-path/rg.exe": {
                "sha256": "14231169855ec5205cf5a1b6f1db358ff4aed4247c86b69ce8aae647c77f6680",
                "size": 4218880,
            },
        },
    },
    "win32/arm64": {
        "filename": "openai_codex_cli_bin-0.160.0-py3-none-win_arm64.whl",
        "url": "https://files.pythonhosted.org/packages/7b/06/87c8137481a5ed334e2e61bf22859b99947f759182ce1c3b12d15e7515d2/openai_codex_cli_bin-0.160.0-py3-none-win_arm64.whl",
        "sha256": "64e9a3b64b92babd7cb3c35b5ee518a3983c891ce1fe839ce052eb4040307391",
        "size": 138102109,
        "members": {
            "codex_cli_bin/bin/codex.exe": {
                "sha256": "1f090167e94ed25969c47381868c6ffb78be2a195e13891fcdc969531ca16eaf",
                "size": 274925872,
            },
            "codex_cli_bin/codex-path/rg.exe": {
                "sha256": "d33a29a9ef03c9f4c03be9e8d88498e6e2d2e566d64cdbdef97f9afc8f13120c",
                "size": 3859456,
            },
        },
    },
    "darwin/arm64": {
        "filename": "openai_codex_cli_bin-0.160.0-py3-none-macosx_11_0_arm64.whl",
        "url": "https://files.pythonhosted.org/packages/26/a1/105c05e179242f0a030cf4a2f7c2bcd574b1001e30379cb4959624294048/openai_codex_cli_bin-0.160.0-py3-none-macosx_11_0_arm64.whl",
        "sha256": "c9b472e8928d8f94f65e43ba4928e3ecac071ccf8680bbb8281334e32cec409b",
        "size": 121753021,
        "members": {
            "codex_cli_bin/bin/codex": {
                "sha256": "112fae7a5a1223e673c8a1791d32338f37df8b527ff1159bb8adac6c4dbf1b4b",
                "size": 241555024,
            },
            "codex_cli_bin/codex-path/rg": {
                "sha256": "7c7d5b09c3a57de864500c65dc2e9c4d2a5e96a3fc7b7d5318480c19887a739b",
                "size": 4030432,
            },
        },
    },
    "darwin/x86_64": {
        "filename": "openai_codex_cli_bin-0.160.0-py3-none-macosx_10_9_x86_64.whl",
        "url": "https://files.pythonhosted.org/packages/ed/83/9fb994efa9da1e21a44c4a610d9884e398168503b90ebe31f4edeb289370/openai_codex_cli_bin-0.160.0-py3-none-macosx_10_9_x86_64.whl",
        "sha256": "06571f34b99feee1f1116577f66b82b1b6d582993e07d2099e20e346c73de374",
        "size": 132620323,
        "members": {
            "codex_cli_bin/bin/codex": {
                "sha256": "5383ef71dd1bd8d2f3658c04a219e2cf165c7969aebd0cceced1bc9f0f68877f",
                "size": 260633072,
            },
            "codex_cli_bin/codex-path/rg": {
                "sha256": "752ed62687b44ffd417352d444db825a7b75ca7b859c7a9f1f4edec77ba5e01d",
                "size": 4437184,
            },
        },
    },
    "linux/x86_64": {
        "filename": "openai_codex_cli_bin-0.160.0-py3-none-manylinux_2_17_x86_64.whl",
        "url": "https://files.pythonhosted.org/packages/82/36/a9d77dd01f0397f178d52ce3da543fec1e59cfa7b85bd4125b97a30957c2/openai_codex_cli_bin-0.160.0-py3-none-manylinux_2_17_x86_64.whl",
        "sha256": "b0664ef64a57f1d00ebac1b783089557b97a53872383bb7cbe288e4015769a15",
        "size": 139465828,
        "members": {
            "codex_cli_bin/bin/codex": {
                "sha256": "12eb3e81114588aca3b7998f4f19e8997b056aca08e57a7ca7c8a3ec8c652aad",
                "size": 289101384,
            },
            "codex_cli_bin/codex-path/rg": {
                "sha256": "e62198eb19b136b88c330af83647b5a962cb99b6b1f066758568f12de1974849",
                "size": 5408904,
            },
        },
    },
    "linux/aarch64": {
        "filename": "openai_codex_cli_bin-0.160.0-py3-none-manylinux_2_17_aarch64.whl",
        "url": "https://files.pythonhosted.org/packages/a2/e5/4e93ad22c849636d26ca993e78eaa285d9ec035d3a8a0faa885cd4e3ef56/openai_codex_cli_bin-0.160.0-py3-none-manylinux_2_17_aarch64.whl",
        "sha256": "6543e1d7f9ffb3f84c61b0234b62fd95c1d5f896310392cc8b03605100293f32",
        "size": 129958661,
        "members": {
            "codex_cli_bin/bin/codex": {
                "sha256": "50b06603bdcdac39b714f5c3e68583c002b8ad8779ebfdaaf4932ff016b379c0",
                "size": 248966648,
            },
            "codex_cli_bin/codex-path/rg": {
                "sha256": "e36d0eb52e70696bdf1781392722e05a21bb91d3b7b762ef5ec20e5df2ec687b",
                "size": 4506992,
            },
        },
    },
}
