"""Write src/coscribe/code_runtime/_pins.py for one Codex CLI release.

Streams each platform's `openai-codex-cli-bin` wheel from PyPI, checks it
against PyPI's own sha256, and records the sha256/size of the two members
coscribe keeps (the `codex` binary and its bundled `rg`). The code module
then downloads just those members and checks them against these values, so
a pin is only ever made from a wheel whose full hash matched.

    python scripts/pin_codex.py 0.160.0

Upgrading Codex is this script plus a re-run of the code module's tests and
a live turn: the app-server protocol is marked experimental upstream.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
import urllib.request
import zipfile
from pathlib import Path

PACKAGE = "openai-codex-cli-bin"
# Platform tag suffix of the wheel -> (sys.platform, machine) keys the
# installer matches on. musllinux is left out: the desktop app ships for
# Windows and macOS, and glibc Linux covers development and CI.
PLATFORMS = {
    "win_amd64": ("win32", "amd64"),
    "win_arm64": ("win32", "arm64"),
    "macosx_11_0_arm64": ("darwin", "arm64"),
    "macosx_10_9_x86_64": ("darwin", "x86_64"),
    "manylinux_2_17_x86_64": ("linux", "x86_64"),
    "manylinux_2_17_aarch64": ("linux", "aarch64"),
}
MEMBERS = ("codex_cli_bin/bin/codex", "codex_cli_bin/codex-path/rg")
OUT = Path(__file__).resolve().parent.parent / "src/coscribe/code_runtime/_pins.py"


def _wheels(version: str) -> dict[str, dict[str, object]]:
    url = f"https://pypi.org/pypi/{PACKAGE}/{version}/json"
    with urllib.request.urlopen(url, timeout=60) as response:
        release = json.load(response)
    found = {}
    for entry in release["urls"]:
        for tag in PLATFORMS:
            if entry["filename"].endswith(f"-py3-none-{tag}.whl"):
                found[tag] = entry
    return found


def _pin_one(entry: dict[str, object]) -> dict[str, object]:
    digest = hashlib.sha256()
    with tempfile.TemporaryFile() as spool:
        with urllib.request.urlopen(str(entry["url"]), timeout=600) as response:
            while chunk := response.read(1 << 20):
                digest.update(chunk)
                spool.write(chunk)
        expected = entry["digests"]["sha256"]  # type: ignore[index]
        if digest.hexdigest() != expected:
            raise SystemExit(f"{entry['filename']}: sha256 {digest.hexdigest()} != PyPI {expected}")
        spool.seek(0)
        members = {}
        with zipfile.ZipFile(spool) as wheel:
            names = wheel.namelist()
            for stem in MEMBERS:
                name = next(n for n in names if n in (stem, stem + ".exe"))
                data = wheel.read(name)
                members[name] = {"sha256": hashlib.sha256(data).hexdigest(), "size": len(data)}
    return {
        "filename": entry["filename"],
        "url": entry["url"],
        "sha256": expected,
        "size": entry["size"],
        "members": members,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    version = parser.parse_args().version
    wheels = _wheels(version)
    missing = sorted(set(PLATFORMS) - set(wheels))
    if missing:
        raise SystemExit(f"{PACKAGE} {version} has no wheel for: {', '.join(missing)}")
    pins = {}
    for tag, (platform, machine) in PLATFORMS.items():
        print(f"{tag}: {wheels[tag]['filename']}", flush=True)
        pins[f"{platform}/{machine}"] = _pin_one(wheels[tag])
    body = json.dumps(pins, indent=4)
    OUT.write_text(
        '"""Generated by scripts/pin_codex.py -- do not edit by hand."""\n\n'
        "from typing import Any\n\n"
        f'CODEX_VERSION = "{version}"\n\n'
        f"WHEELS: dict[str, dict[str, Any]] = {body}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
